### ISSUE TITLE
Just reading my game log and saw this:

### ISSUE THREAD

**Issue by Taje01taje** [RootsTeam/Embers#258] opened 2017-10-30 01:11 UTC
21:09:26 | FML | main | warn | * A broken ore dictionary registration with name nuggetIron has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry. TO USERS: YES this is a BUG in the mod Embers report it to them!
-- | -- | -- | -- | --
21:09:26 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
21:09:26 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
21:09:26 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
21:09:26 | FML | main | warn | *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:512)
21:09:26 | FML | main | warn | *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
21:09:26 | FML | main | warn | *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
21:09:26 | FML | main | warn | ****************************************
21:09:26 | FML | main | warn | ****************************************
21:09:26 | FML | main | warn | * A broken ore dictionary registration with name dustAsh has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry. TO USERS: YES this is a BUG in the mod Embers report it to them!
21:09:26 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
21:09:26 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
21:09:26 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
21:09:26 | FML | main | warn | *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:513)
21:09:26 | FML | main | warn | *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
21:09:26 | FML | main | warn | *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
21:09:26 | FML | main | warn | ****************************************
21:09:26 | FML | main | warn | ****************************************
21:09:26 | FML | main | warn | * A broken ore dictionary registration with name dustAshes has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry. TO USERS: YES this is a BUG in the mod Embers report it to them!
21:09:26 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
21:09:26 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
21:09:26 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
21:09:26 | FML | main | warn | *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:514)
21:09:26 | FML | main | warn | *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
21:09:26 | FML | main | warn | *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
21:09:26 | FML | main | warn | ****************************************

**Comment by elucent** [comment] 2017-10-30 02:00
Duplicate of #234

**Closed by elucent** 2017-10-30 02:00 UTC
