### ISSUE TITLE
Is finding more than 20% on the Atmosphere gauge supposed to be super rare?

### ISSUE THREAD

**Issue by Dragnier** [RootsTeam/Embers#105] opened 2017-02-03 20:00 UTC
I've started a few worlds now in both 1.10.2 and 1.11.2 versions of Embers. In all of them I've had to travel at least 3000-4000 blocks to find any reading above approx. 20% on the gauge. One of those worlds had lots of Extreme Hills but the best none of the readings were worth stopping for.

I did eventually find a reading that was probably about 30-33% of the gauge (in a plains no less)... but 4000 blocks seems like a lot of travel not to find at least a 50% reading somewhere. Plus, that 4000 was only the straight line distance from spawn, not the actual route I took; so I actually checked far more than just 4000 in a straight line.

**Comment by elucent** [comment] 2017-02-05 04:27
Yeah this is _effectively_ how it's supposed to work. You don't need more than about 20% on the gauge to get started, and I did plan some additional means of tracking down spikes to come.

I think I need to come up with a better system for Ember spawning in general though. It's not the best at the moment, but I haven't figured out a better functionality yet.

I'm gonna close this since it's technically intended behavior, but do note that I will try and change this up in the future.

**Closed by elucent** 2017-02-05 04:27 UTC
