### ISSUE TITLE
Crash when using with IncreaseMobs (Edit)

### ISSUE THREAD

**Issue by sharkck** [RootsTeam/Embers#235] opened 2017-07-15 18:03 UTC
Whenever I enable this mod, Biomes O Plenty crashes on worldgen.  Here is the logfile:

[crash-2017-07-15_14.01.37-server.txt](https://github.com/RootsTeam/Embers/files/1150510/crash-2017-07-15_14.01.37-server.txt)

**Comment by elucent** [comment] 2017-07-15 18:52
I don't see anything in your crashlog that would indicate that Embers is causing the crash, nor does Embers do anything that would potentially cause a crash like this. Are you sure you cannot reproduce it without Embers?

**Comment by sharkck** [comment] 2017-07-15 19:24
I add Embers and it crashes.  I remove Embers and it works fine.  I'm not sure what else I can do to further identify the issue.

**Comment by sharkck** [comment] 2017-07-15 21:14
I'm working on another way to troubleshoot this.  As soon as I have more info I'll post here.

**Comment by sharkck** [comment] 2017-07-16 00:37
Apparently the mod, IncreaseMobs by _kegare is causing the crash.  Whenever I enable that mod, it crashes both this mod and another with the reported crash log above.

https://mods.curse.com/mc-mods/minecraft/244509-increasemobs

Only took about 4 hours to find it... lol

**Comment by elucent** [comment] 2017-10-30 02:03
I don't see evidence that this is my fault. Closing.

**Closed by elucent** 2017-10-30 02:03 UTC
