### ISSUE TITLE
Codex Issues

### ISSUE THREAD

**Issue by WhiskersRS** [RootsTeam/Embers#122] opened 2017-03-13 01:08 UTC
The item description on the bottom is off the screen.
The alchemy injector page is not displaying properly.

I was warned the eye was removed when loading 202. With the removal of the eye the research table is no longer craft-able, is that intentional?

Just a suggestion, I personally see the recipe for the codex as unnecessarily high considering it is a "how to" guide for beginners. You should not need to make an alchemy component to create it, as it forces someone  unfamiliar with this mod to make half of the machines you have in the mod to just create the "how to" guide. I would suggest replacing the core with just a large ember crystal so it can be a created near the beginning of exploring this mod, much like the eye was.

![2017-03-12_19 56 20](https://cloud.githubusercontent.com/assets/25867491/23837991/a975ab96-075e-11e7-8261-2b37c9c679d4.png)
![2017-03-12_19 56 14](https://cloud.githubusercontent.com/assets/25867491/23837993/b0759320-075e-11e7-8581-58cf60a0bdf8.png)

**Comment by elucent** [comment] 2017-03-13 01:41
It does not require an alchemy component -- both items needed to create it are very common drops from Ancient Golems. You can use alchemy to make more of them without having to kill more golems, but that's not the intended method of making the components.

The research table is removed, it's useless with the Codex.

The item description being off the bottom of the screen might just be an issue with your GUI scale. I suppose I can force it to fit onscreen but it might overlap a few researches.

The injector entries will be fixed by the time I finish this response.

The darkening of entries is...tricky to solve. I already plaster my code with color-resetting functions to try and avoid it, but it happens regardless. Doesn't help that I can't reproduce the bug in my dev environment. I'll see if I can fix it in the future.

**Comment by elucent** [comment] 2017-03-13 01:41
Marking this as an issue for the darkening of the GUI.

**Comment by WhiskersRS** [comment] 2017-03-13 01:55
That is good news, I was unaware those were drops at all. I just started exploring this mod this weekend (after loving roots 2) and have yet to run into an Ancient Golem.

The screen resolution was  1920x1080 with the GUI scale set to auto.

**Comment by elucent** [comment] 2017-03-13 02:18
Huh, I have the same resolution and GUI scale and it works for me. I've changed the bar to render dynamically depending on window size, so it should always be onscreen. I also tweaked some render calls and might have fixed the darkening problem, but it's hard to say since I couldn't reproduce the problem in the first place.

Gonna put out a v0.205 right away, let me know if the darkening is fixed.

**Closed by elucent** 2017-03-13 02:18 UTC
Labels: 1.11.2, bug

**Comment by WhiskersRS** [comment] 2017-03-13 03:04
All 3 issues have been fixed. :)
The codex looks very nice!

![2017-03-12_21 54 01](https://cloud.githubusercontent.com/assets/25867491/23839849/ca95cae4-076e-11e7-9092-f33ebc0ada4e.png)

**Comment by elucent** [comment] 2017-03-13 03:18
Thanks! Glad I could help.
