### ISSUE TITLE
(Renamed) Ember Dials not providing accurate reading (Previously: Activated ember transmitting when target is full)

### ISSUE THREAD

**Issue by ScribeOfSeshat** [RootsTeam/Embers#209] opened 2017-06-19 04:54 UTC
In both 0.215 and 0.216 with forge 13.20.0.2315 (MC 1.11.2), activated ember is transmitting when the target (copper cell, splitter, machine) is already full (according to the dial: splitter at 400.0/400.0 and copper cell at 24000/24000). Attempting to fix this by breaking the receptor and re-placing it causes ember to transmit to it before using the hammer to connect it to the emitter. It is also possible that splitters feeding to themselves is related (a splitter will occasionally send ember to its own receptor despite the connection directing the ember elsewhere). The source of the activated ember does not seem to effect this. So far I have tested this with the ignem reactor and the pressure refinery. This issue continues in a new creative world and so is unrelated to save corruption. The issue continues when embers is the only mod active (i.e. it is not due to a mod conflict).

**Comment by ScribeOfSechat** [comment] 2017-06-19 12:07
Update: Upon further testing, it appears that the ember does stop transmitting some time after the dials on the receiving end read full, suggesting that the issue is not in ember transmission as it first seemed, but rather, that the dials are not providing an accurate measure of the amount of ember stored

**Comment by elucent** [comment] 2017-06-26 19:15
The Ember Receptor has a small internal buffer that fills up after the block it is attached to is full. Try attaching a dial to the Ember Receptor to see if it filling is indeed the cause of your problem.

**Comment by ScribeOfSeshat** [comment] 2017-07-03 03:24
Okay, that might be it. So far I haven't had any further issues. Being aware of the buffer, I will want to do some further testing, but yes, it appears that this might be responsible.

**Comment by elucent** [comment] 2017-07-03 04:01
Closing for now, please reopen if the situation changes.

**Closed by elucent** 2017-07-03 04:01 UTC
Labels: 1.11.2
