### ISSUE TITLE
Crash when Stamp Base is broken

### ISSUE THREAD

**Issue by eyekantspel** [RootsTeam/Embers#40] opened 2016-11-21 00:09 UTC
```
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at teamroots.embers.tileentity.TileEntityStampBaseRenderer.func_180535_a(TileEntityStampBaseRenderer.java:37)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:168)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:141)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:996)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1730)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1336)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at teamroots.embers.tileentity.TileEntityStampBaseRenderer.func_180535_a(TileEntityStampBaseRenderer.java:37)

-- Block Entity Details --
Details:
	Name: embers:tileEntityStampBase // teamroots.embers.tileentity.TileEntityStampBase
	Block type: ID #833 (tile.stamperBase // teamroots.embers.block.BlockStampBase)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-38,64,218), Chunk: (at 10,4,10 in -3,13; contains blocks -48,0,208 to -33,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:168)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:141)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:996)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1730)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [EntityPlayerSP['eyekantspel343'/460987, l='MpServer', x=-33.71, y=65.50, z=220.36], EntityOtherPlayerMP['Ninbyo'/448961, l='MpServer', x=-23.03, y=30.00, z=217.25], EntityOtherPlayerMP['RoyAwesome'/493566, l='MpServer', x=-36.70, y=64.00, z=220.31]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (56,64,256), Chunk: (at 8,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2970318 game time, 3027283 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 148 total; [EntityBat['Bat'/463366, l='MpServer', x=-9.71, y=34.10, z=234.53], EntitySkeleton['Skeleton'/616971, l='MpServer', x=-109.50, y=35.00, z=185.50], EntityZombie['Zombie'/617473, l='MpServer', x=-2.50, y=37.00, z=290.50], EntityZombie['Zombie'/617472, l='MpServer', x=0.50, y=37.00, z=288.50], EntityCyberZombie['Zombie'/617478, l='MpServer', x=-99.50, y=24.00, z=202.50], EntityOtherPlayerMP['RoyAwesome'/493566, l='MpServer', x=132.43, y=70.00, z=201.55], EntityHorse['Skeleton Horse'/362525, l='MpServer', x=-48.55, y=62.49, z=288.61], EntityCreeper['Creeper'/617489, l='MpServer', x=40.50, y=45.00, z=287.50], EntityCyberZombie['Zombie'/617490, l='MpServer', x=44.50, y=45.00, z=288.50], EntityAbyssalZombie['Abyssal Zombie'/556055, l='MpServer', x=-17.90, y=27.20, z=290.92], EntityItem['item.item.egg'/618027, l='MpServer', x=-15.75, y=66.00, z=232.75], EntityItem['item.tile.stonebrick'/618026, l='MpServer', x=-24.88, y=30.00, z=220.88], EntityItem['item.item.feather'/611886, l='MpServer', x=16.51, y=66.00, z=269.88], EntityCreeper['Creeper'/618019, l='MpServer', x=-67.50, y=24.00, z=257.50], EntityItem['item.tile.stonebrick'/617508, l='MpServer', x=-24.85, y=30.00, z=219.88], EntitySpider['Spider'/617531, l='MpServer', x=-0.30, y=20.10, z=172.09], EntitySpider['Spider'/617530, l='MpServer', x=3.50, y=18.00, z=172.50], EntityCreeper['Creeper'/617532, l='MpServer', x=0.51, y=18.00, z=171.30], EntityPlayerSP['eyekantspel343'/460987, l='MpServer', x=-13.74, y=67.00, z=246.64], EntityAbyssalZombie['Abyssal Zombie'/618032, l='MpServer', x=-111.16, y=29.00, z=249.06], EntityOtherPlayerMP['RoyAwesome'/484601, l='MpServer', x=-10.13, y=62.00, z=235.08], EntitySkeleton['Skeleton'/594484, l='MpServer', x=-0.75, y=33.00, z=237.50], EntityAbyssalZombie['Abyssal Zombie'/617032, l='MpServer', x=-110.32, y=29.00, z=250.20], EntitySkeleton['Skeleton'/562754, l='MpServer', x=-17.53, y=33.00, z=233.78], EntityChicken['Chicken'/75, l='MpServer', x=-76.96, y=62.68, z=207.54], EntityOtherPlayerMP['RoyAwesome'/473242, l='MpServer', x=-21.80, y=62.00, z=234.30], EntityZombie['Zombie'/78, l='MpServer', x=-68.70, y=21.00, z=290.30], EntityChicken['Chicken'/79, l='MpServer', x=-65.43, y=63.00, z=286.17], EntityItem['item.item.corflesh'/613465, l='MpServer', x=-66.95, y=36.00, z=210.53], EntityCyberZombie['Zombie'/574555, l='MpServer', x=15.78, y=41.00, z=288.50], EntityConcussionCreeper['Concussion Creeper'/491602, l='MpServer', x=-14.40, y=33.00, z=233.30], EntitySkeleton['Skeleton'/609887, l='MpServer', x=-18.70, y=57.00, z=292.28], EntityItem['item.tile.stonebrick'/618068, l='MpServer', x=-24.88, y=30.29, z=220.88], EntityOtherPlayerMP['RoyAwesome'/493566, l='MpServer', x=-36.70, y=64.00, z=220.31], EntityPig['Pig'/108, l='MpServer', x=-75.44, y=62.59, z=290.18], EntityChicken['Chicken'/109, l='MpServer', x=-52.47, y=62.57, z=278.29], EntityAbyssalZombie['Abyssal Zombie'/556668, l='MpServer', x=-13.30, y=40.00, z=296.70], EntityCreeper['Creeper'/617087, l='MpServer', x=-46.50, y=43.00, z=283.50], EntityCreeper['Creeper'/617086, l='MpServer', x=-41.50, y=43.00, z=285.50], EntityItem['item.tile.stamperBase'/618103, l='MpServer', x=-37.19, y=65.10, z=218.61], EntityOtherPlayerMP['Ninbyo'/448961, l='MpServer', x=-20.73, y=65.00, z=217.54], EntitySkeleton['Skeleton'/617088, l='MpServer', x=-45.50, y=43.00, z=282.50], EntityAbyssalZombie['Abyssal Zombie'/616578, l='MpServer', x=-18.65, y=38.00, z=285.91], EntityZombie['Zombie'/617606, l='MpServer', x=-41.45, y=37.00, z=292.76], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/147, l='MpServer', x=-34.50, y=63.50, z=236.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/148, l='MpServer', x=-34.50, y=63.50, z=233.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/149, l='MpServer', x=-33.50, y=63.50, z=238.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/150, l='MpServer', x=-34.50, y=63.50, z=248.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/151, l='MpServer', x=-34.50, y=63.50, z=245.50], EntityArmorStand['Armor Stand'/366226, l='MpServer', x=-7.50, y=62.00, z=232.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/152, l='MpServer', x=-34.50, y=63.50, z=242.50], EntityOtherPlayerMP['RoyAwesome'/493566, l='MpServer', x=-29.47, y=64.00, z=234.51], EntityZombie['Zombie'/557732, l='MpServer', x=-28.26, y=60.00, z=294.45], EntityItem['item.item.corflesh'/614073, l='MpServer', x=-56.48, y=33.00, z=211.64], EntityItem['item.item.rottenFlesh'/614074, l='MpServer', x=-57.13, y=32.00, z=211.45], EntityCreeper['Creeper'/617136, l='MpServer', x=-59.50, y=52.00, z=290.50], EntityZombie['Zombie'/617655, l='MpServer', x=-113.68, y=35.00, z=217.53], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/192, l='MpServer', x=-31.50, y=63.50, z=239.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/193, l='MpServer', x=-31.50, y=63.50, z=236.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/194, l='MpServer', x=-31.50, y=63.50, z=233.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/203, l='MpServer', x=-31.50, y=63.50, z=242.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/204, l='MpServer', x=-31.50, y=63.50, z=245.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/205, l='MpServer', x=-31.50, y=63.50, z=248.50], EntityChicken['Chicken'/209, l='MpServer', x=-16.45, y=62.00, z=274.34], EntityItem['item.item.egg'/611032, l='MpServer', x=-75.37, y=60.00, z=207.96], EntityAbyssalZombie['Abyssal Zombie'/210, l='MpServer', x=-18.85, y=11.10, z=290.15], EntityItem['item.item.egg'/615632, l='MpServer', x=-78.40, y=62.00, z=236.09], EntityItem['item.item.corflesh'/612064, l='MpServer', x=-57.66, y=32.00, z=213.27], EntityZombie['Zombie'/617211, l='MpServer', x=-84.50, y=17.00, z=295.50], EntitySkeleton['Skeleton'/617212, l='MpServer', x=-85.50, y=17.00, z=296.50], EntityChicken['Chicken'/464127, l='MpServer', x=-16.91, y=66.00, z=232.82], EntityChicken['Chicken'/464126, l='MpServer', x=-15.83, y=66.00, z=233.33], EntityDepthsGhoul['Depths Ghoul'/250, l='MpServer', x=-14.50, y=44.00, z=286.50], EntityBat['Bat'/510202, l='MpServer', x=-5.51, y=34.10, z=235.52], EntityDepthsGhoul['Depths Ghoul'/259, l='MpServer', x=-17.09, y=57.00, z=291.86], EntityCartChest['Chest Cart'/260, l='MpServer', x=-14.50, y=40.06, z=317.50], EntityChicken['Chicken'/464129, l='MpServer', x=-15.83, y=66.00, z=232.82], EntityChicken['Chicken'/464128, l='MpServer', x=-15.83, y=66.00, z=233.94], EntityPig['Pig'/265, l='MpServer', x=-15.30, y=66.00, z=296.39], EntityBat['Bat'/617735, l='MpServer', x=-34.37, y=34.43, z=293.99], EntityCreeper['Creeper'/616221, l='MpServer', x=-15.50, y=44.00, z=287.50], EntityItem['item.tile.stonebrick'/617757, l='MpServer', x=-21.17, y=30.00, z=219.88], EntityChicken['Chicken'/464159, l='MpServer', x=-16.28, y=66.00, z=233.06], EntityChicken['Chicken'/464155, l='MpServer', x=-16.48, y=66.00, z=233.93], EntityArmorStand['Armor Stand'/365345, l='MpServer', x=-8.50, y=62.00, z=232.50], EntityChicken['Chicken'/127781, l='MpServer', x=16.52, y=66.00, z=269.20], EntityOtherPlayerMP['RoyAwesome'/453906, l='MpServer', x=-23.24, y=62.24, z=234.30], EntityItem['item.tile.stonebrick'/617761, l='MpServer', x=-22.86, y=30.00, z=219.88], EntitySkeleton['Skeleton'/614716, l='MpServer', x=-99.50, y=30.00, z=220.50], EntityChicken['Chicken'/310, l='MpServer', x=19.52, y=64.00, z=217.87], EntityChicken['Chicken'/464176, l='MpServer', x=-17.03, y=66.00, z=233.88], EntityCartChest['Chest Cart'/312, l='MpServer', x=29.50, y=33.06, z=249.50], EntityChicken['Chicken'/314, l='MpServer', x=-7.89, y=67.00, z=298.15], EntityItem['item.item.egg'/608050, l='MpServer', x=16.98, y=66.00, z=269.58], EntityItem['item.item.rottenFlesh'/612151, l='MpServer', x=-55.10, y=33.00, z=215.46], EntityItem['item.item.corflesh'/612150, l='MpServer', x=-54.49, y=33.00, z=215.16], EntityHorse['Skeleton Horse'/329, l='MpServer', x=45.28, y=61.35, z=234.60], EntityBat['Bat'/616261, l='MpServer', x=-90.44, y=48.12, z=290.50], EntityAbyssalZombie['Abyssal Zombie'/555845, l='MpServer', x=-11.78, y=39.00, z=271.52], EntitySpider['Spider'/617286, l='MpServer', x=-110.80, y=29.00, z=246.87], EntityCartChest['Chest Cart'/337, l='MpServer', x=43.51, y=46.00, z=289.49], EntityItem['item.item.egg'/613207, l='MpServer', x=-16.88, y=62.00, z=274.35], EntityBat['Bat'/616790, l='MpServer', x=-24.22, y=38.51, z=184.48], EntityCartChest['Chest Cart'/352, l='MpServer', x=58.50, y=34.06, z=243.50], EntityChicken['Chicken'/464736, l='MpServer', x=-16.78, y=66.00, z=233.28], EntityCreeper['Creeper'/616291, l='MpServer', x=-15.53, y=33.00, z=234.80], EntityZombie['Zombie'/616290, l='MpServer', x=6.50, y=25.00, z=281.50], EntityCreeper['Creeper'/616293, l='MpServer', x=-26.50, y=32.00, z=234.50], EntityCreeper['Creeper'/616292, l='MpServer', x=-23.82, y=32.00, z=234.59], EntityCyberZombie['Zombie'/376682, l='MpServer', x=-16.64, y=12.51, z=295.70], EntityZombie['Zombie'/614777, l='MpServer', x=-35.57, y=19.00, z=290.82], EntityItem['item.tile.stonebrick'/617343, l='MpServer', x=-23.58, y=30.00, z=218.88], EntitySquid['Squid'/616841, l='MpServer', x=-92.69, y=60.00, z=188.22], EntityItem['item.tile.stonebrick'/617353, l='MpServer', x=-24.88, y=30.00, z=218.40], EntitySquid['Squid'/616840, l='MpServer', x=-83.55, y=60.81, z=197.53], EntityItem['item.item.egg'/617352, l='MpServer', x=-51.76, y=62.00, z=277.40], EntityAbyssalZombie['Abyssal Zombie'/617857, l='MpServer', x=-19.65, y=38.00, z=286.35], EntityAbyssalZombie['Abyssal Zombie'/617347, l='MpServer', x=-112.28, y=29.00, z=250.20], EntitySquid['Squid'/616839, l='MpServer', x=-84.71, y=60.82, z=207.35], EntitySkeleton['Skeleton'/615833, l='MpServer', x=-14.06, y=33.00, z=234.07], EntitySkeleton['Skeleton'/615832, l='MpServer', x=-7.50, y=33.00, z=234.50], EntityConcussionCreeper['Concussion Creeper'/615834, l='MpServer', x=-9.30, y=33.00, z=234.50], EntityPlayerSP['eyekantspel343'/460987, l='MpServer', x=-33.71, y=65.50, z=220.36], EntitySkeleton['Skeleton'/616352, l='MpServer', x=-93.50, y=14.00, z=152.50], EntityOtherPlayerMP['RoyAwesome'/478930, l='MpServer', x=-20.46, y=62.00, z=233.41], EntityChicken['Chicken'/371625, l='MpServer', x=-32.19, y=64.00, z=223.48], EntityZombie['Zombie'/609700, l='MpServer', x=-55.70, y=32.00, z=213.30], EntityItem['item.tile.flower2.poppy'/615846, l='MpServer', x=-96.13, y=27.00, z=212.91], EntityItem['item.item.rottenFlesh'/613821, l='MpServer', x=-56.13, y=32.00, z=212.88], EntityItem['item.item.corflesh'/613820, l='MpServer', x=-57.13, y=32.00, z=211.87], EntityBat['Bat'/617919, l='MpServer', x=34.16, y=43.26, z=290.56], EntityItem['item.tile.stonebrick'/617904, l='MpServer', x=-23.13, y=30.00, z=220.88], EntityOtherPlayerMP['Ninbyo'/448961, l='MpServer', x=-23.03, y=30.00, z=217.25], EntityBat['Bat'/617922, l='MpServer', x=-102.66, y=27.78, z=198.61], EntityItem['item.tile.stonebrick'/617944, l='MpServer', x=-21.95, y=30.00, z=219.55], EntityChicken['Chicken'/154064, l='MpServer', x=-79.25, y=62.64, z=235.61], EntitySkeleton['Skeleton'/472020, l='MpServer', x=-25.49, y=32.00, z=237.29], EntitySkeleton['Skeleton'/617439, l='MpServer', x=-20.83, y=39.00, z=182.45], EntityZombie['Zombie'/617438, l='MpServer', x=-21.77, y=39.00, z=181.50], EntityItem['item.tile.stonebrick'/617937, l='MpServer', x=-23.06, y=32.00, z=219.92], EntityCreeper['Creeper'/615380, l='MpServer', x=24.50, y=17.00, z=171.50], EntityPig['Pig'/443366, l='MpServer', x=-97.45, y=62.00, z=280.79], EntityPig['Pig'/443365, l='MpServer', x=-98.52, y=62.00, z=276.71], EntityOtherPlayerMP['Ninbyo'/448961, l='MpServer', x=-23.03, y=30.00, z=217.25], EntityZombie['Zombie'/617969, l='MpServer', x=-36.50, y=23.00, z=260.50], EntityOtherPlayerMP['RoyAwesome'/493566, l='MpServer', x=-36.70, y=64.00, z=220.31], EntityZombie['Zombie'/617970, l='MpServer', x=-37.50, y=23.00, z=260.50], EntityZombie['Zombie'/617973, l='MpServer', x=-38.08, y=23.00, z=263.80]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```
[crash-2016-11-20_19.03.08-client.txt](https://github.com/RootsTeam/Embers/files/602428/crash-2016-11-20_19.03.08-client.txt)

**Comment by elucent** [comment] 2016-11-21 04:23
How exactly did you break it?

**Comment by eyekantspel** [comment] 2016-11-22 04:09
Vanilla Iron Pickaxe

**Comment by elucent** [comment] 2016-11-22 05:38
That is...very strange. I can't replicate it in any way. However, I can see what the problem is from your log -- it *should* hypothetically be fixed now.

**Closed by elucent** 2016-11-22 05:38 UTC
