### ISSUE TITLE
[Bug] Melter duplication glitch 

### ISSUE THREAD

**Issue by absolutedespair** [RootsTeam/Embers#108] opened 2017-02-10 15:08 UTC
Hi. Currently playing on ATM:expert modpack (Embers V0.104)
Dropping items one by one on top of Melter dupes them. 
https://youtu.be/e76W09eS8To

**Comment by elucent** [comment] 2017-02-24 06:48
I have not been able to replicate this anywhere outside of the ATM:Expert modpack. Considering that I have received several other reports in the past from this modpack specifically, I am pretty sure the issue is with the ATM:Expert tweak mod and not Embers itself. It may be fixed in the future, I'm not sure, but it's not on my end.

**Closed by elucent** 2017-02-24 06:48 UTC

**Comment by al132** [comment] 2017-02-24 08:16
This may be a problem with ATM: Expert tweaks, but I think it's more likely that you're getting a lot of reports from ATM:E because outside of ATM and ATM:E there are hardly any sizable packs (I took a peek at the dependencies) that use Embers, let alone force you to use it as part of the progression like in ATM:E. I haven't updated the ATM:E tweaks, but I put the source up on github a while ago. Let me know if you see any related problems. https://github.com/al132/ATMExpertTweaks/blob/master/src/main/java/al132/atmexperttweaks/CommonProxy.java#L73

**Comment by elucent** [comment] 2017-02-24 08:23
I've seen plenty of people who _have_ been using it outside of ATM and ATM:E who haven't run into a problem, and I _have_ been trying to replicate this. I have never been able to replicate it. Now, I _am_ a bit curious, because now that I see your source it doesn't _look_ like it should be causing any problems.

It might be possible that this bug was fixed in a later update -- by which I mean, a 1.11.2 one. I mean, I wasn't able to reproduce this in any 1.10 versions either, but I am nearly completely sure that this can't happen anymore. So, since I'm not actively maintaining 1.10 anymore, I stand by closing this issue. Sorry if it proves an issue for you still.
