### ISSUE TITLE
[1.12.1] Ore Dictionary Error

### ISSUE THREAD

**Issue by Preminenc3** [RootsTeam/Embers#243] opened 2017-08-16 23:03 UTC
[17:52:24] [main/WARN] [FML]: ****************************************
[17:52:24] [main/WARN] [FML]: * A broken ore dictionary registration with name nuggetIron has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[17:52:24] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[17:52:24] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[17:52:24] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[17:52:24] [main/WARN] [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:512)
[17:52:24] [main/WARN] [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[17:52:24] [main/WARN] [FML]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[17:52:24] [main/WARN] [FML]: ****************************************
[17:52:24] [main/WARN] [FML]: ****************************************
[17:52:24] [main/WARN] [FML]: * A broken ore dictionary registration with name dustAsh has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[17:52:24] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[17:52:24] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[17:52:24] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[17:52:24] [main/WARN] [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:513)
[17:52:24] [main/WARN] [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[17:52:24] [main/WARN] [FML]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[17:52:24] [main/WARN] [FML]: ****************************************
[17:52:24] [main/WARN] [FML]: ****************************************
[17:52:24] [main/WARN] [FML]: * A broken ore dictionary registration with name dustAshes has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[17:52:24] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[17:52:24] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[17:52:24] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[17:52:24] [main/WARN] [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:514)
[17:52:24] [main/WARN] [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[17:52:24] [main/WARN] [FML]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[17:52:24] [main/WARN] [FML]: ****************************************

**Comment by UnPure** [comment] 2017-09-28 18:45
I can confirm this issue.

While starting a server/client, embers is producing these errors/warnings.

https://pastebin.com/qgXnNqtP

**Roots:** 0.221
**Forge:** 14.22.0.2475

**Comment by bookerthegeek** [comment] 2017-10-21 06:27
### Heyo ###
Still an issue. Using embers-0.221on a SpongeForge installation


```
[23:12:01] [main/WARN] [FML]: ****************************************
[23:12:01] [main/WARN] [FML]: * A broken ore dictionary registration with name nuggetIron has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[23:12:01] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
[23:12:01] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
[23:12:01] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
[23:12:01] [main/WARN] [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:512)
[23:12:01] [main/WARN] [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[23:12:01] [main/WARN] [FML]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[23:12:01] [main/WARN] [FML]: ****************************************
[23:12:01] [main/WARN] [FML]: ****************************************
[23:12:01] [main/WARN] [FML]: * A broken ore dictionary registration with name dustAsh has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[23:12:01] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
[23:12:01] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
[23:12:01] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
[23:12:01] [main/WARN] [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:513)
[23:12:01] [main/WARN] [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[23:12:01] [main/WARN] [FML]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[23:12:01] [main/WARN] [FML]: ****************************************
[23:12:01] [main/WARN] [FML]: ****************************************
[23:12:01] [main/WARN] [FML]: * A broken ore dictionary registration with name dustAshes has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[23:12:01] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
[23:12:01] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
[23:12:01] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
[23:12:01] [main/WARN] [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:514)
[23:12:01] [main/WARN] [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[23:12:01] [main/WARN] [FML]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[23:12:01] [main/WARN] [FML]: ****************************************
```

**Comment by elucent** [comment] 2017-10-30 02:00
Duplicate of #234

**Closed by elucent** 2017-10-30 02:00 UTC
