### ISSUE TITLE
Broken ore dictionary registration errors

### ISSUE THREAD

**Issue by sharkck** [RootsTeam/Embers#242] opened 2017-08-02 07:50 UTC
As requested by the logfile, reporting this issue.  Hope this helps!

[03:34:52] [Server thread/WARN] [FML]: ****************************************
[03:34:52] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name nuggetIron has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[03:34:52] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[03:34:52] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[03:34:52] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[03:34:52] [Server thread/WARN] [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:512)
[03:34:52] [Server thread/WARN] [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[03:34:52] [Server thread/WARN] [FML]: *  at teamroots.embers.proxy.ServerProxy.preInit(ServerProxy.java:10)...
[03:34:52] [Server thread/WARN] [FML]: ****************************************
[03:34:52] [Server thread/WARN] [FML]: ****************************************
[03:34:52] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name dustAsh has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[03:34:52] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[03:34:52] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[03:34:52] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[03:34:52] [Server thread/WARN] [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:513)
[03:34:52] [Server thread/WARN] [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[03:34:52] [Server thread/WARN] [FML]: *  at teamroots.embers.proxy.ServerProxy.preInit(ServerProxy.java:10)...
[03:34:52] [Server thread/WARN] [FML]: ****************************************
[03:34:52] [Server thread/WARN] [FML]: ****************************************
[03:34:52] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name dustAshes has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[03:34:52] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[03:34:52] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[03:34:52] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[03:34:52] [Server thread/WARN] [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:514)
[03:34:52] [Server thread/WARN] [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[03:34:52] [Server thread/WARN] [FML]: *  at teamroots.embers.proxy.ServerProxy.preInit(ServerProxy.java:10)...
[03:34:52] [Server thread/WARN] [FML]: ****************************************

**Comment by elucent** [comment] 2017-10-30 02:00
Duplicate of #234

**Closed by elucent** 2017-10-30 02:00 UTC
